apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prom-stack
    meta.helm.sh/release-namespace: observability
  creationTimestamp: "2024-06-13T09:10:02Z"
  generation: 3
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: kube-prom-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 45.5.0
    chart: kube-prometheus-stack-45.5.0
    heritage: Helm
    release: kube-prom-stack
  name: kube-prom-stack-kube-prome-prometheus
  namespace: observability
  resourceVersion: "2199685"
  uid: dd894128-f83c-461b-87e7-e7af5a48b31b
spec:
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: kube-prom-stack-kube-prome-alertmanager
      namespace: observability
      pathPrefix: /
      port: http-web
  enableAdminAPI: false
  evaluationInterval: 30s
  externalUrl: http://kube-prom-stack-kube-prome-prometheus.observability:9090
  hostNetwork: false
  image: quay.io/prometheus/prometheus:v2.42.0
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: kube-prom-stack
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: kube-prom-stack
  replicas: 1
  retention: 1d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: kube-prom-stack
  scrapeInterval: 10s
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: kube-prom-stack-kube-prome-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: kube-prom-stack
  shards: 1
  version: v2.42.0
  walCompression: true
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-06-24T08:33:59Z"
    observedGeneration: 3
    status: "True"
    type: Available
  - lastTransitionTime: "2024-06-13T09:10:44Z"
    observedGeneration: 3
    status: "True"
    type: Reconciled
  paused: false
  replicas: 1
  shardStatuses:
  - availableReplicas: 1
    replicas: 1
    shardID: "0"
    unavailableReplicas: 0
    updatedReplicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
